### ISSUE TITLE
No candidate version available for influxdb

### ISSUE THREAD

**Issue by dmigous** [bdangit/chef-influxdb#144]
Hello
Facing following error on Debian:

```
  * chef_gem[influxdb] action install
    - install version 0.3.14 of package influxdb
  * influxdb_install[influxdb] action install
    * apt_package[apt-transport-https] action install (up to date)
    * apt_repository[influxdb] action add (skipped due to only_if)
    * apt_package[influxdb] action install
      * No candidate version available for influxdb
      ================================================================================
      Error executing action `install` on resource 'apt_package[influxdb]'
      ================================================================================
      
      Chef::Exceptions::Package
      -------------------------
      No candidate version available for influxdb
      
      Resource Declaration:
      ---------------------
      # In /chef/local-mode-cache/cache/cookbooks/influxdb/resources/install.rb
      
       47:     package 'influxdb' do
       48:       version node['influxdb']['version'] if node['influxdb']['version']
       49:       options '--force-yes -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold"' if node.platform_family? 'debian'
       50:     end
       51:   when 'file'
      
      Compiled Resource:
      ------------------
      # Declared in /chef/local-mode-cache/cache/cookbooks/influxdb/resources/install.rb:47:in `block in class_from_file'
      
      apt_package("influxdb") do
        package_name "influxdb"
        action [:install]
        default_guard_interpreter :default
        declared_type :package
        cookbook_name "influxdb"
        options ["--force-yes", "-o", "Dpkg::Options::=--force-confdef", "-o", "Dpkg::Options::=--force-confold"]
      end
      
      System Info:
      ------------
      chef_version=13.0.118
      platform=debian
      platform_version=8.7
      ruby=ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-linux]
      program_name=chef-solo worker: ppid=6;start=15:26:28;
      executable=/opt/chef/bin/chef-solo
      
    
    ================================================================================
    Error executing action `install` on resource 'influxdb_install[influxdb]'
    ================================================================================
    
    Chef::Exceptions::Package
    -------------------------
    apt_package[influxdb] (/chef/local-mode-cache/cache/cookbooks/influxdb/resources/install.rb line 47) had an error: Chef::Exceptions::Package: No candidate version available for influxdb
    
    Resource Declaration:
    ---------------------
    # In /chef/local-mode-cache/cache/cookbooks/influxdb/recipes/default.rb
    
     13: influxdb_install 'influxdb' do
     14:   include_repository node['influxdb']['include_repository']
     15:   install_version node['influxdb']['version']
     16:   install_type node['influxdb']['install_type']
     17:   action [:install]
     18: end
     19: 
    
    Compiled Resource:
    ------------------
    # Declared in /chef/local-mode-cache/cache/cookbooks/influxdb/recipes/default.rb:13:in `from_file'
    
    influxdb_install("influxdb") do
      action [:install]
      default_guard_interpreter :default
      declared_type :influxdb_install
      cookbook_name "influxdb"
      recipe_name "default"
      include_repository nil
      install_version nil
      install_type "package"
      arch_type "amd64"
    end
    
    System Info:
    ------------
    chef_version=13.0.118
    platform=debian
    platform_version=8.7
    ruby=ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-linux]
    program_name=chef-solo worker: ppid=6;start=15:26:28;
    executable=/opt/chef/bin/chef-solo
    

Running handlers:
[2017-04-24T15:26:48+00:00] ERROR: Running exception handlers
Running handlers complete
[2017-04-24T15:26:48+00:00] ERROR: Exception handlers complete
Chef Client failed. 4 resources updated in 20 seconds
[2017-04-24T15:26:48+00:00] FATAL: Stacktrace dumped to /chef/local-mode-cache/cache/chef-stacktrace.out
[2017-04-24T15:26:48+00:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
[2017-04-24T15:26:48+00:00] ERROR: influxdb_install[influxdb] (influxdb::default line 13) had an error: Chef::Exceptions::Package: apt_package[influxdb] (/chef/local-mode-cache/cache/cookbooks/influxdb/resources/install.rb line 47) had an error: Chef::Exceptions::Package: No candidate version available for influxdb
[2017-04-24T15:26:49+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
```

**Comment by bdangit** [comment]
Hi @dmigous, what is `node['influxdb']['version']` set to?

**Comment by dmigous** [comment]
@bdangit I don't set it. Here is to what I simplified my recipe to still get error:

```
root@99e2a942f218:/chef# cat ./docker-cookbooks/delorean/recipes/influxdb.rb
include_recipe 'influxdb'

influxdb_install 'influxdb' do
  arch_type 'amd64' # if undefined will auto detect
  include_repository true # default
  influxdb_key 'https://repos.influxdata.com/influxdb.key' # default
  action :install # default
end
```

**Comment by bdangit** [comment]
Thanks @dmigous I'm able to repro this error using latest chef client. It looks like influxdata guys updated install instructions for Debian as I am able to install it manually as per instructions. Check back in a week to get a PR cut.

**Comment by dmigous** [comment]
@bdangit many thanks

**Comment by bdangit** [comment]
@dmigous Influxdata didn't do anything new.  It is Chef 13 just doing somethings to ensure expectations are set clearly.  Feel free to have a look at PR #146.  Feedback / Comments apperciated!

**Comment by bdangit** [comment]
`6.0.0` is published.  have it a go @dmigous
