### ISSUE TITLE
Checksum Fail

### ISSUE THREAD

**Issue by gkope** [bdangit/chef-influxdb#39]
```shell
Recipe: influxdb::default
  * influxdb[main] action create
  Recipe: <Dynamically Defined Resource>
    * remote_file[/var/chef/cache/influxdb.deb] action create

      ================================================================================
      Error executing action `create` on resource 'remote_file[/var/chef/cache/influxdb.deb]'
      ================================================================================

      Chef::Exceptions::ChecksumMismatch
      ----------------------------------
      Checksum on resource (58ae03) does not match checksum on content (8faf14)

      Cookbook Trace:
      ---------------
      /home/gkope/chef-solo/cookbooks-3/influxdb/providers/default.rb:50:in `install_influxdb'
      /home/gkope/chef-solo/cookbooks-3/influxdb/providers/default.rb:33:in `block in class_from_file'

      Compiled Resource:
      ------------------
      # Declared in

      remote_file("/var/chef/cache/influxdb.deb") do
        provider Chef::Provider::RemoteFile
        action "create"
        retries 0
        retry_delay 2
        default_guard_interpreter :default
        path "/var/chef/cache/influxdb.deb"
        backup 5
        atomic_update true
        source ["http://s3.amazonaws.com/influxdb/influxdb_latest_amd64.deb"]
        use_etag true
        use_last_modified true
        checksum "58ae034557e6a2886530577ab368ed2153b4e0a41bcfa57d8b15a9d5006f14d0"
      end


    ================================================================================
    Error executing action `create` on resource 'influxdb[main]'
    ================================================================================

    Chef::Exceptions::ChecksumMismatch
    ----------------------------------
    remote_file[/var/chef/cache/influxdb.deb] (dynamically defined) had an error: Chef::Exceptions::ChecksumMismatch: Checksum on resource (58ae03) does not match checksum on content (8faf14)

    Cookbook Trace:
    ---------------
    /home/gkope/chef-solo/cookbooks-3/influxdb/providers/default.rb:50:in `install_influxdb'
    /home/gkope/chef-solo/cookbooks-3/influxdb/providers/default.rb:33:in `block in class_from_file'

    Resource Declaration:
    ---------------------
    # In /home/gkope/chef-solo/cookbooks-3/influxdb/recipes/default.rb

     26: influxdb 'main' do
     27:   source node[:influxdb][:source]
     28:   checksum node[:influxdb][:versions][arch][ver]
     29:   config node[:influxdb][:config]
     30:   action [:create]
     31: end

    Compiled Resource:
    ------------------
    # Declared in /home/gkope/chef-solo/cookbooks-3/influxdb/recipes/default.rb:26:in `from_file'

    influxdb("main") do
      action [:create]
      retries 0
      retry_delay 2
      default_guard_interpreter :default
      cookbook_name :influxdb
      recipe_name "default"
      source "http://s3.amazonaws.com/influxdb/influxdb_latest_amd64.deb"
      checksum "58ae034557e6a2886530577ab368ed2153b4e0a41bcfa57d8b15a9d5006f14d0"
      config {"bind-address"=>"0.0.0.0", "reporting-disabled"=>false, "logging"=>{"level"=>"info", "file"=>"/opt/influxdb/shared/log.txt"}, "admin"=>{"port"=>8083}, "api"=>{"port"=>8086, "read-timeout"=>"5s"}, "input_plugins"=>{"graphite"=>{"enabled"=>false}, "udp"=>{"enabled"=>false}}, "raft"=>{"port"=>8090, "dir"=>"/opt/influxdb/shared/data/raft"}, "storage"=>{"dir"=>"/opt/influxdb/shared/data/db", "write-buffer-size"=>10000, "default-engine"=>"rocksdb", "max-open-shards"=>0, "point-batch-size"=>100, "write-batch-size"=>5000000, "retention-sweep-period"=>"10m", "engines"=>{"leveldb"=>{"max-open-files"=>1000, "lru-cache-size"=>"200m"}, "rocksdb"=>{"max-open-files"=>1000, "lru-cache-size"=>"200m"}, "hyperleveldb"=>{"max-open-files"=>1000, "lru-cache-size"=>"200m"}, "lmdb"=>{"map-size"=>"100g"}}}, "cluster"=>{"protobuf_port"=>8099, "protobuf_timeout"=>"2s", "protobuf_heartbeat"=>"200ms", "protobuf_min_backoff"=>"1s", "protobuf_max_backoff"=>"10s", "write-buffer-size"=>1000, "max-response-buffer-size"=>100, "concurrent-shard-query-limit"=>10}, "wal"=>{"dir"=>"/opt/influxdb/shared/data/wal", "flush-after"=>1000, "bookmark-after"=>1000, "index-after"=>1000, "requests-per-logfile"=>10000}}
    end


Running handlers:
[2014-12-10T13:36:55+00:00] ERROR: Running exception handlers
Running handlers complete
[2014-12-10T13:36:55+00:00] ERROR: Exception handlers complete
[2014-12-10T13:36:55+00:00] FATAL: Stacktrace dumped to /var/chef/cache/chef-stacktrace.out
Chef Client failed. 11 resources updated in 6.446269177 seconds
[2014-12-10T13:36:55+00:00] ERROR: influxdb[main] (influxdb::default line 26) had an error: Chef::Exceptions::ChecksumMismatch: remote_file[/var/chef/cache/influxdb.deb] (dynamically defined) had an error: Chef::Exceptions::ChecksumMismatch: Checksum on resource (58ae03) does not match checksum on content (8faf14)
[2014-12-10T13:36:55+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
ERROR: RuntimeError: chef-solo failed. See output above.
```

I fixed the problem adding the correct checksum on node:
```json
{
    "influxdb": {
        "versions": {
            "amd64": {
                "latest": "8faf1468b2f81d468dea34055671ab88831172c8905919021914a2a3e41707fa"
            }
        }
    },
    "run_list": [
        "influxdb"
    ]
}
```

Do we really need to have a checksum on this recipe? Normally, the latest version is always named latest, so there's no way to keep the checksum always up to date...

Thanks,

**Comment by bdangit** [comment]
fixed as per PR has been merged
