### ISSUE TITLE
ArgumentError influxdb_config create on chef 12.6

### ISSUE THREAD

**Issue by cyberflow** [bdangit/chef-influxdb#93]
Hello.

I have a problem when i try to use cookbook with chef-zero 12.6.0:

```
================================================================================
           Error executing action `create` on resource 'influxdb_config[/etc/influxdb/influxdb.conf]'
           ================================================================================

           ArgumentError
           -------------
           wrong number of arguments (1 for 0)

           Cookbook Trace:
           ---------------
           /tmp/kitchen/cache/cookbooks/compat_resource/files/lib/chef_compat/copied_from_chef/chef/resource_builder.rb:39:in `initialize'
           /tmp/kitchen/cache/cookbooks/compat_resource/files/lib/chef_compat/copied_from_chef/chef/resource_builder.rb:39:in `initialize'
           /tmp/kitchen/cache/cookbooks/compat_resource/files/lib/chef_compat/copied_from_chef/chef/dsl/declare_resource.rb:100:in `new'
           /tmp/kitchen/cache/cookbooks/compat_resource/files/lib/chef_compat/copied_from_chef/chef/dsl/declare_resource.rb:100:in `build_resource'
           /tmp/kitchen/cache/cookbooks/compat_resource/files/lib/chef_compat/copied_from_chef/chef/dsl/declare_resource.rb:67:in `declare_resource'
           /tmp/kitchen/cache/cookbooks/influxdb/resources/config.rb:28:in `block in class_from_file'
           /tmp/kitchen/cache/cookbooks/compat_resource/files/lib/chef_compat/copied_from_chef/chef/provider.rb:118:in `instance_eval'
           /tmp/kitchen/cache/cookbooks/compat_resource/files/lib/chef_compat/copied_from_chef/chef/provider.rb:118:in `compile_and_converge_action'

           Resource Declaration:
           ---------------------
           # In /tmp/kitchen/cache/cookbooks/influxdb/recipes/default.rb

            52: influxdb_config node['influxdb']['config_file_path'] do
            53:   config node['influxdb']['config']
            54: end
            55:

           Compiled Resource:
           ------------------
           # Declared in /tmp/kitchen/cache/cookbooks/influxdb/recipes/default.rb:52:in `from_file'

           influxdb_config("/etc/influxdb/influxdb.conf") do
             action [:create]
             retries 0
             retry_delay 2
             default_guard_interpreter :default
             declared_type :influxdb_config
             cookbook_name "influxdb"
             recipe_name "default"
             config {"reporting-disabled"=>false, "meta"=>{"dir"=>"/var/lib/influxdb/meta", "hostname"=>"localhost", "bind-address"=>":8088", "retention-autocreate"=>true, "election-timeout"=>"1s", "heartbeat-timeout"=>"1s", "leader-lease-timeout"=>"500ms", "commit-timeout"=>"50ms"}, "data"=>{"dir"=>"/var/lib/influxdb/data", "max-wal-size"=>104857600, "wal-flush-interval"=>"10m", "wal-partition-flush-delay"=>"2s", "wal-dir"=>"/var/lib/influxdb/wal", "wal-enable-logging"=>true}, "cluster"=>{"shard-writer-timeout"=>"5s", "write-timeout"=>"5s"}, "retention"=>{"enabled"=>true, "check-interval"=>"30m"}, "monitor"=>{"store-enabled"=>true, "store-database"=>"_internal", "store-interval"=>"10s"}, "admin"=>{"enabled"=>true, "bind-address"=>":8083", "https-enabled"=>false, "https-certificate"=>"/etc/ssl/influxdb.pem"}, "http"=>{"enabled"=>true, "bind-address"=>":8086", "auth-enabled"=>false, "log-enabled"=>true, "write-tracing"=>false, "pprof-enabled"=>false, "https-enabled"=>false, "https-certificate"=>"/etc/ssl/influxdb.pem"}, "graphite"=>[{"enabled"=>false}], "collectd"=>{"enabled"=>false}, "opentsdb"=>{"enabled"=>false}, "udp"=>[{"enabled"=>false}], "continuous_queries"=>{"log-enabled"=>true, "enabled"=>true, "recompute-previous-n"=>2, "recompute-no-older-than"=>"10m", "compute-runs-per-interval"=>10, "compute-no-more-than"=>"2m"}, "hinted-handoff"=>{"enabled"=>true, "dir"=>"/var/lib/influxdb/hh", "max-size"=>1073741824, "max-age"=>"168h", "retry-rate-limit"=>0, "retry-interval"=>"1s"}}
             path "/etc/influxdb/influxdb.conf"
           end
```

Could you help me fix this problem?
Thanks.

**Comment by bdangit** [comment]
hey @cyberflow thanks for reporting, we will take a look soon.

**Comment by fishnix** [comment]
This looks like an issue with compat_resource cookbook, that is included to support versions of Chef older than 12.5.  See this issue https://github.com/chef-cookbooks/compat_resource/issues/37

**Comment by bdangit** [comment]
I see same result when `depends 'compat_resource'` is set.  When I remove it, 12.6 support works.  Looking at the compat_resource cookbook, it doesn't look like we can turn it off.

**Comment by bdangit** [comment]
This PR #102 will address 12.6 chef client compability until they resolve the compat_resource issue.

**Comment by bdangit** [comment]
This is fixed temporarily until chef, inc. fixes `compat_resoource`.  Will close this now and when it breaks we'll check to see latest status.
